export {default as getBanner} from './banner'
export {default as getSetting} from './setting'
export {default as about} from './about'
export {default as getProject} from './project'
export {default as message} from './message'